// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/match/:id": {
    params: {
      "id": string;
    };
  };
  "/match/:id/reviews": {
    params: {
      "id": string;
    };
  };
  "/rounds": {
    params: {};
  };
  "/teams": {
    params: {};
  };
  "/teams/:id": {
    params: {
      "id": string;
    };
  };
  "/players": {
    params: {};
  };
  "/players/:id": {
    params: {
      "id": string;
    };
  };
  "/login": {
    params: {};
  };
  "/login/callback": {
    params: {};
  };
  "/signup": {
    params: {};
  };
  "/profile": {
    params: {};
  };
  "/about": {
    params: {};
  };
  "/*": {
    params: {
      "*": string;
    };
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/match/:id" | "/match/:id/reviews" | "/rounds" | "/teams" | "/teams/:id" | "/players" | "/players/:id" | "/login" | "/login/callback" | "/signup" | "/profile" | "/about" | "/*";
  };
  "routes/home.tsx": {
    id: "routes/home";
    page: "/";
  };
  "routes/match-detail.tsx": {
    id: "routes/match-detail";
    page: "/match/:id";
  };
  "routes/match-reviews.tsx": {
    id: "routes/match-reviews";
    page: "/match/:id/reviews";
  };
  "routes/rounds.tsx": {
    id: "routes/rounds";
    page: "/rounds";
  };
  "routes/teams.tsx": {
    id: "routes/teams";
    page: "/teams";
  };
  "routes/team-detail.tsx": {
    id: "routes/team-detail";
    page: "/teams/:id";
  };
  "routes/players.tsx": {
    id: "routes/players";
    page: "/players";
  };
  "routes/player-detail.tsx": {
    id: "routes/player-detail";
    page: "/players/:id";
  };
  "routes/login.tsx": {
    id: "routes/login";
    page: "/login";
  };
  "routes/login-callback.tsx": {
    id: "routes/login-callback";
    page: "/login/callback";
  };
  "routes/signup.tsx": {
    id: "routes/signup";
    page: "/signup";
  };
  "routes/profile.tsx": {
    id: "routes/profile";
    page: "/profile";
  };
  "routes/about.tsx": {
    id: "routes/about";
    page: "/about";
  };
  "routes/not-found.tsx": {
    id: "routes/not-found";
    page: "/*";
  };
};

type RouteModules = {
  "root": typeof import("./app/root.tsx");
  "routes/home": typeof import("./app/routes/home.tsx");
  "routes/match-detail": typeof import("./app/routes/match-detail.tsx");
  "routes/match-reviews": typeof import("./app/routes/match-reviews.tsx");
  "routes/rounds": typeof import("./app/routes/rounds.tsx");
  "routes/teams": typeof import("./app/routes/teams.tsx");
  "routes/team-detail": typeof import("./app/routes/team-detail.tsx");
  "routes/players": typeof import("./app/routes/players.tsx");
  "routes/player-detail": typeof import("./app/routes/player-detail.tsx");
  "routes/login": typeof import("./app/routes/login.tsx");
  "routes/login-callback": typeof import("./app/routes/login-callback.tsx");
  "routes/signup": typeof import("./app/routes/signup.tsx");
  "routes/profile": typeof import("./app/routes/profile.tsx");
  "routes/about": typeof import("./app/routes/about.tsx");
  "routes/not-found": typeof import("./app/routes/not-found.tsx");
};